The Next Web
BrianSammit/TNW pull request #1
Opened 2020-08-10 23:46 UTC by BrianSammit

The project consists of creating a responsive website of The Next Web that changes the position and size of the items and images.

2020-08-14 18:45 UTC, MuriloRoque requested changes
# Status: Changes requested :red_circle: 

## Hello @BrianSammit and @alvinlouis29 :wave: 

## You have done an amazing job so far :grin: , it's hard to spot differences between your page and the original. However, I still noticed some details that I need you to fix :eyeglasses:  Please, let me help you:

# Page

- I really liked the effects when changing screen sizes :smile: 

- [ ] You need to add the TNW logo inside of the big image to the left, just like the original. See below:

## Yours:
![Screenshot from 2020-08-14 15-03-15](https://user-images.githubusercontent.com/59691171/90279381-7fffd500-de3f-11ea-9f50-f4c187ccd47f.png)

## Original:
![Screenshot from 2020-08-14 15-03-22](https://user-images.githubusercontent.com/59691171/90279419-9017b480-de3f-11ea-8a7d-5c9c08c28fbd.png)
<br>

## NOTE: This logo is ONLY present in large screens :warning: 

<br> 

- [ ] In the Latest News section, you need to fill the entire width of the screen with the articles. In your transition from medium to a large screen, they are not centered as the original because of this:
## Yours:
![Screenshot from 2020-08-14 15-16-37](https://user-images.githubusercontent.com/59691171/90280832-f4d40e80-de41-11ea-9d22-88ea12ac3356.png)
![Screenshot from 2020-08-14 15-17-09](https://user-images.githubusercontent.com/59691171/90280850-f8679580-de41-11ea-8178-9dd1c4842092.png)

## Orignal:

![Screenshot from 2020-08-14 15-16-46](https://user-images.githubusercontent.com/59691171/90280857-fe5d7680-de41-11ea-9b49-7b4f2a91eab7.png)
![Screenshot from 2020-08-14 15-17-12](https://user-images.githubusercontent.com/59691171/90280866-02899400-de42-11ea-9ea7-bfaa1362c20c.png)
<br>
- [ ] The same thing happens in the Latest Funding section, they are not aligned in the transition between medium and large screens:
## Yours:

![Screenshot from 2020-08-14 15-27-59](https://user-images.githubusercontent.com/59691171/90281456-f94cf700-de42-11ea-8bee-ba56be33902d.png)
## Original:
![Screenshot from 2020-08-14 15-27-56](https://user-images.githubusercontent.com/59691171/90281474-036ef580-de43-11ea-8301-0fe54e078d0a.png)
<br>

- [ ] I will not repeat myself in this review. But the same issue above is happening in the next two sections, please fix them! :wink: 

## General

- Nice job with the README file, looks very professional :+1: 
- Good PR and commit messages :heavy_check_mark: 

## Section

- [ ] Please, check your live link in the README file, I believe it's not the same as the one I cloned. I saw some differences.
- Your HTML is awesome, keep up the good work!

- [ ] I made some comments in your CSS file, please take a look :grin: 

# Summary

- You are in the right direction, everything looks in place, just some minor fixes and you will be good to go :rocket: 

## Kindly make the requested changes and submit for another review, please :pray: 

## I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-14 18:45 UTC, MuriloRoque commented on css/styles.css
> +}
- [ ] Please avoid repeating the same properties, put them all together :wink:

2020-08-14 18:45 UTC, MuriloRoque commented on css/styles.css
> +  }
- [ ] Same problem as above, repeating properties.

2020-08-14 23:15 UTC, BrianSammit commented
We fix the sizing problems on the page and we add the image to the left on large screens.
Also, we take out the repeating properties.

2020-08-15 09:27 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

## Hello again @BrianSammit and @alvinlouis29 :wave: 

## Thank you for making the required changes I asked you. Congratulations, your project is approved :clap: You may merge! 

## Note: Please update your live link :grin: :warning: 

## Good luck in your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-15 13:21 UTC, merged